web:
  build: .
  links:
   - db
   - redis
  ports:
   - "80:8000"
  volumes:
   - .:/usr/src/app/
  environment:
    NODE_ENV: production
    MONGO_URL: mongodb://db/hnrg
    REDIS_URL: redis://redis
    TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
    NTBA_FIX_319: "true"
    URL: ${URL_BASE}
db:
  image: mongo:latest
redis:
  image: redis:latest

