version: '3'
volumes:
  mongo-db:
services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile-development
    image: hnrg_grupo74_dev
    links:
      - db
      - redis
    ports:
      - 8000:8000
    volumes:
      - ..:/usr/src/app/
    environment:
      NODE_ENV: development
      MONGO_URL: mongodb://db/hnrg
      REDIS_URL: redis://redis
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      NTBA_FIX_319: "true"
      URL: ${URL_BASE}
  db:
    image: mongo:latest
    volumes:
      - mongo-db:/data/db
    ports:
    - 27017:27017
  mongo-express:
    image: mongo-express
    links:
      - db:mongo
    ports:
      - 8081:8081
  redis:
    image: redis:latest
